[[redirects]]
  from = "/api/getNewJoke"
  to = "/.netlify/functions/getNewJoke"
  status = 200

[[headers]]
    # Define which paths this specific [[headers]] block will cover.
    for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Origin, Access-Control-Allow-Origin, X-Requested-With, Content-Type, Accept, Authorization, authorization"
    Access-Control-Allow-Methods = "GET , DELETE, POST, OPTIONS"