[[redirects]]
  from = "/api/getNewJoke"
  to = "/.netlify/functions/getNewJoke"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Methods = "POST, PUT, DELETE, GET, OPTIONS"
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "*"